### ISSUE TITLE
http://gazebosim.org/wiki/Tutorials/drcsim/joint_control  manifest error

### ISSUE THREAD

**Issue by osrf-migration** [osrf/drcsim#8]
**Original report ([archived issue](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/issues/8)) by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
I'm having trouble running the joint control tutorial. The following command fails:

    #!c++
    http://gazebosim.org/wiki/Tutorials/drcsim/joint_control

The stack trace points to this file 

    #!c++
    /usr/share/drcsim-0.9.0/ros/drc_robot_utils/manifest.xml

It has an extra </package> at the end. Removing it fixes the problem.

Here's the error message:

rosrun joint_control_tutorial joint_control.py
Traceback (most recent call last):
  File "/home/hugo/ros/joint_control_tutorial/scripts/joint_control.py", line 4, in <module>
    roslib.load_manifest('joint_control_tutorial')
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/roslib/launcher.py", line 98, in _generate_python_path
    packages = get_depends(pkg, rospack) 
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/roslib/launcher.py", line 51, in get_depends
    vals = rospack.get_depends(package, implicit=True)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 186, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 180, in get_depends
    names = [p.name for p in self.get_manifest(name).depends]
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 118, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 157, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 351, in parse_manifest_file
    return parse_manifest(manifest_name, f.read(), filename)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 370, in parse_manifest
    raise InvalidManifest("[%s] invalid XML: %s"%(filename, e))
rospkg.manifest.InvalidManifest: [/usr/share/drcsim-0.9.0/ros/drc_robot_utils/manifest.xml] invalid XML: not well-formed (invalid token): line 21, column 1
hugo@hugobox:~/ros/joint_control_tutorial$

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
Fixed in 29dd9d4109d484491b72b5e30bf986dd5d4e3315

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
Fixed in 29dd9d4109d484491b72b5e30bf986dd5d4e3315

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------

* changed state from "new" to "resolved"
