### ISSUE TITLE
drcsim/ros/drc_robot_utils/manifest.xml dependency not found: joint_state_publisher

### ISSUE THREAD

**Issue by osrf-migration** [osrf/drcsim#9]
**Original report ([archived issue](https://osrf-migration.github.io/drcsim-gh-pages/#!/osrf/drcsim/issues/9)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
I also just ran into trouble with the joint_control tutorial with the error message given below. It has trouble finding the ros package "joint_state_publisher" referenced in drcsim/ros/drc_robot_utils/manifest.xml

I'm running a fresh install according to the installation instructions, and I don't seem to have that ros package. The tutorial seems to work if the line containing "<depend package="joint_state_publisher"/>" is commented out of manifest.xml

Traceback (most recent call last):
  File "/home/scpeters/ros/joint_control_tutorial/scripts/joint_control.py", line 3, in <module>
    import roslib; roslib.load_manifest('joint_control_tutorial')
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/roslib/launcher.py", line 98, in _generate_python_path
    packages = get_depends(pkg, rospack) 
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/roslib/launcher.py", line 51, in get_depends
    vals = rospack.get_depends(package, implicit=True)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 186, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 186, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 180, in get_depends
    names = [p.name for p in self.get_manifest(name).depends]
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 118, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 157, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 149, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: joint_state_publisher
ROS path [0]=/opt/ros/fuerte/share/ros
ROS path [1]=~/ros
ROS path [2]=/usr/share/drcsim-0.9.0/ros
ROS path [3]=/usr/share/drcsim-0.9.0/models/fire_hose
ROS path [4]=/usr/share/drcsim-0.9.0/models/drc_robot
ROS path [5]=/usr/share/drcsim-0.9.0/models/drc_terrain
ROS path [6]=/usr/share/drcsim-0.9.0/models/low_poly_golf_cart
ROS path [7]=/usr/share/drcsim-0.9.0/models/camhand
ROS path [8]=/usr/share/drcsim-0.9.0/models/standpipe
ROS path [9]=/opt/ros/fuerte/share
ROS path [10]=/opt/ros/fuerte/stacks

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
Good catch!  We're missing a deb dependency on ros-fuerte-robot-model-visualization.  Added in #!/osrf/drcsim-release/changeset/e278a00830bf706955b77d6422821f6d

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------

* changed state from "new" to "resolved"
